#!/usr/bin/env python3
"""Build the China outline for the route map in index.html.

Usage: python3 tools/build-map.py path/to/ne_50m_admin_0_countries.geojson

Reads Natural Earth 1:50m country polygons (public domain), clips them to the
map's region, projects them with the SAME projection the page uses for the pins
(see PROJECTION below and the matching `project()` in index.html), simplifies
them, and writes two <path> elements between the outline markers in index.html.
Run it once; the outline never changes unless the projection does.
"""
import json, math, re, sys

# --- PROJECTION: must match project() in index.html -------------------------
LNG0, LAT0, SCALE = 108.0, 30.0, 40.0          # centre and px per degree
KX = math.cos(math.radians(LAT0))              # east-west correction
def project(lng, lat):
    return ((lng - LNG0) * KX * SCALE, (LAT0 - lat) * SCALE)

# --- region kept (generous margin around the route) -------------------------
CLIP = (96.0, 19.0, 127.0, 43.5)               # lng min, lat min, lng max, lat max
CHINA = {"CHN", "TWN", "HKG", "MAC"}
NEIGHBOURS = {"MNG", "VNM", "LAO", "MMR", "PRK", "KOR", "JPN", "PHL", "IND", "NPL",
              "BTN", "BGD", "RUS", "KAZ", "KGZ", "TJK", "AFG", "PAK", "THA"}
TOLERANCE = 1.4                                # px, Douglas-Peucker

def clip_ring(ring, box):
    """Sutherland-Hodgman clip of a lng/lat ring against a rectangle."""
    x0, y0, x1, y1 = box
    def clip(points, inside, intersect):
        out = []
        if not points: return out
        prev = points[-1]
        for cur in points:
            if inside(cur):
                if not inside(prev): out.append(intersect(prev, cur))
                out.append(cur)
            elif inside(prev):
                out.append(intersect(prev, cur))
            prev = cur
        return out
    def ix(p, q, x):
        t = (x - p[0]) / (q[0] - p[0]); return (x, p[1] + t * (q[1] - p[1]))
    def iy(p, q, y):
        t = (y - p[1]) / (q[1] - p[1]); return (p[0] + t * (q[0] - p[0]), y)
    r = ring
    r = clip(r, lambda p: p[0] >= x0, lambda p, q: ix(p, q, x0))
    r = clip(r, lambda p: p[0] <= x1, lambda p, q: ix(p, q, x1))
    r = clip(r, lambda p: p[1] >= y0, lambda p, q: iy(p, q, y0))
    r = clip(r, lambda p: p[1] <= y1, lambda p, q: iy(p, q, y1))
    return r

def dp(points, tol):
    if len(points) < 3: return points
    def perp(p, a, b):
        ax, ay = a; bx, by = b; px, py = p
        dx, dy = bx - ax, by - ay
        if dx == dy == 0: return math.hypot(px - ax, py - ay)
        t = max(0, min(1, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
        return math.hypot(px - (ax + t * dx), py - (ay + t * dy))
    keep = [False] * len(points); keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        i, j = stack.pop()
        if j <= i + 1: continue
        k, dmax = -1, 0
        for m in range(i + 1, j):
            d = perp(points[m], points[i], points[j])
            if d > dmax: k, dmax = m, d
        if dmax > tol:
            keep[k] = True; stack += [(i, k), (k, j)]
    return [p for p, k in zip(points, keep) if k]

def rings_of(geom):
    if geom["type"] == "Polygon": return [geom["coordinates"][0]]
    return [poly[0] for poly in geom["coordinates"]]   # outer rings only

def to_path(features):
    parts = []
    for f in features:
        for ring in rings_of(f["geometry"]):
            r = clip_ring([tuple(p) for p in ring], CLIP)
            if len(r) < 3: continue
            pts = dp([project(*p) for p in r], TOLERANCE)
            if len(pts) < 3: continue
            parts.append("M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + "Z")
    return "".join(parts)

def main():
    src, page = sys.argv[1], "index.html"
    data = json.load(open(src))
    by = {f["properties"]["ADM0_A3"]: f for f in data["features"]}
    china = to_path([by[k] for k in CHINA if k in by])
    nb = to_path([by[k] for k in NEIGHBOURS if k in by])
    block = (f'<!-- outline:start (generated by tools/build-map.py from Natural Earth 1:50m, public domain) -->\n'
             f'<path class="neighbours" d="{nb}"/>\n<path class="china" d="{china}"/>\n<path class="china-grain" d="{china}"/>\n<!-- outline:end -->')
    html = open(page).read()
    new, n = re.subn(r'<!-- outline:start.*?<!-- outline:end -->', lambda m: block, html, flags=re.S)
    assert n == 1, "outline markers not found in index.html"
    open(page, "w").write(new)
    print(f"china path {len(china)/1024:.1f} KB, neighbours {len(nb)/1024:.1f} KB")

if __name__ == "__main__":
    main()
